package com.rb.gui;

import com.rb.Aplication;
import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.border.Border;

/**
 *
 * @author lrod
 */
public class ConfigCont extends javax.swing.JPanel {

    private final Aplication app;

    /**
     * Creates new form ConfigCont
     *
     * @param app
     */
    public ConfigCont(Aplication app) {
        this.app = app;
        initComponents();
        createComponents(false);
    }

    public ConfigCont(Aplication app, boolean selected) {
        this.app = app;
        initComponents();
        createComponents(selected);
    }

    private void createComponents(boolean selected) {

        jCheckBox1.setVisible(selected);

        Border bdMargin = BorderFactory.createEmptyBorder(4, 4, 4, 4);
        Border bdLine = BorderFactory.createLineBorder(Color.darkGray, 1, true);
        setBorder(BorderFactory.createCompoundBorder(bdLine, bdMargin));

        labelDB.setIcon(new ImageIcon(app.getImgManager().getImagen(app.getFolderIcons() + "trafficlight-green.png", 12, 12)));
        labelDB.setHorizontalAlignment(JLabel.CENTER);
    }

    public void addActionListener(ActionListener listener) {
        jCheckBox1.addActionListener(listener);
    }

    public void showSelected(boolean show) {
        jCheckBox1.setVisible(show);
    }

    public void setSelected(boolean selected) {
        jCheckBox1.setSelected(selected);
    }

    public boolean isSelected() {
        return jCheckBox1.isSelected();
    }

    public void setTitle(String title) {
        lbTitle.setText(title);
    }

    public void addCampo(JComponent component) {
        container.add(component);
    }

    public void setBackgroundTitle(Color color) {
        lbTitle.setOpaque(true);
        lbTitle.setBackground(color);
        labelDB.setOpaque(true);
        labelDB.setBackground(color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelDB = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbTitle.setText("jLabel2");

        container.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelDB, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jCheckBox1)
                .addGap(2, 2, 2)
                .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jCheckBox1)
                    .addComponent(labelDB, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTitle))
                .addGap(3, 3, 3)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDB;
    private javax.swing.JLabel lbTitle;
    // End of variables declaration//GEN-END:variables
}
