/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rb.gui;

import java.text.DecimalFormat;
import java.text.NumberFormat;

/**
 *
 * @author lrod
 */
public class PanelListItem extends javax.swing.JPanel {

    /**
     * Creates new form PanelListItem
     */
    public PanelListItem() {
        initComponents();
    }
    
    public void setCantidad(int value) {
        spCantidad.setValue(value);
    }

    public void setNombre(String nombre) {
        lbNombre.setText(nombre);
    }
    
    public void setAdicion(String adicion) {
        lbAdicion.setText(adicion);
    }
    
    public void setNotas(String notas) {
        lbNotas.setText(notas);
    }
    
    public void setPrecio(String precio) {
        NumberFormat NF = DecimalFormat.getCurrencyInstance();
        NF.setMaximumFractionDigits(0);
        lbPrecio.setText(NF.format(Double.valueOf(precio)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spCantidad = new javax.swing.JSpinner();
        lbNombre = new javax.swing.JLabel();
        lbAdicion = new javax.swing.JLabel();
        lbNotas = new javax.swing.JLabel();
        lbPrecio = new javax.swing.JLabel();

        spCantidad.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        lbNombre.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(26, 0, 128));
        lbNombre.setText("jLabel1");

        lbAdicion.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lbAdicion.setForeground(java.awt.Color.darkGray);
        lbAdicion.setText("jLabel1");

        lbNotas.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lbNotas.setForeground(java.awt.Color.darkGray);
        lbNotas.setText("jLabel1");

        lbPrecio.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        lbPrecio.setForeground(new java.awt.Color(184, 25, 2));
        lbPrecio.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(spCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbAdicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(lbNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbNombre)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbAdicion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNotas))
                    .addComponent(lbPrecio)))
            .addComponent(spCantidad)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAdicion;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNotas;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JSpinner spCantidad;
    // End of variables declaration//GEN-END:variables
}
