package com.rb.gui;

import com.rb.Aplication;
import com.rb.domain.Invoice;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.dz.PanelCapturaMod;

/**
 *
 * @author lrod
 */
public class PanelQuickSearch extends PanelCapturaMod implements ActionListener {
    
    private final Aplication app;

    /**
     * Creates new form PanelQuickSearch
     */
    public PanelQuickSearch(Aplication app) {
        this.app = app;
        initComponents();
        createComponents();
        
    }
    
    private void createComponents() {
        regSearch.setFontCampo(new Font("sans", 1, 24));
        regSearch.addActionListener(this);
        regSearch.setActionCommand(AC_SEARCH);
        btBuscar.setActionCommand(AC_SEARCH);
        btBuscar.addActionListener(this);
        
        pnContain.setLayout(new BorderLayout());
        
        btBuscar.setIcon(new ImageIcon(app.getImgManager().getImagen(app.getFolderIcons() + "search.png", 30, 30)));
        pnContain.setVisible(false);
        
        lbInfo.setText("<html></html>");
        
    }
    
    private void doSearch() {
        try {
            if (regSearch.getText() != null) {
                String ticket = regSearch.getText();
                searchInvoice(ticket);
            }
        } catch (Exception ex) {
            
        }
        
    }
    
    private void searchInvoice(String codigo) {
        Invoice invoice = app.getControl().getInvoiceByCode(codigo);
        if (invoice != null) {
            PanelConfirmPedido confirmPedido = new PanelConfirmPedido(app, invoice);
            confirmPedido.addPropertyChangeListener(app.getGuiManager().getPanelPedido());
            pnContain.removeAll();
            pnContain.add(confirmPedido);
        } else {
            pnContain.removeAll();
            lbInfo.setText("<html><font color=red size=+2>Ticket " + codigo + " no encontrado</font></html>");
            pnContain.add(lbInfo);
        }
        pnContain.setVisible(true);        
        updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbInfo = new javax.swing.JLabel();
        regSearch = new org.dz.Registro(BoxLayout.X_AXIS, "Buscar", "", 100);
        btBuscar = new javax.swing.JButton();
        pnContain = new javax.swing.JPanel();

        lbInfo.setText("jLabel1");

        javax.swing.GroupLayout pnContainLayout = new javax.swing.GroupLayout(pnContain);
        pnContain.setLayout(pnContainLayout);
        pnContainLayout.setHorizontalGroup(
            pnContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnContainLayout.setVerticalGroup(
            pnContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnContain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(regSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnContain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void reset() {
        regSearch.setText("");
        pnContain.removeAll();
        pnContain.setVisible(false);
        updateUI();
    }
    
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if (AC_SEARCH.equals(e.getActionCommand())) {
            doSearch();
        }
    }
    
    public static final String AC_SEARCH = "AC_SEARCH";


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JPanel pnContain;
    private org.dz.Registro regSearch;
    // End of variables declaration//GEN-END:variables
}
