/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rb.gui.util;

import com.rb.Aplication;
import com.rb.ProgAction;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Action;
import javax.swing.JLabel;

/**
 *
 * @author ballestax
 */
public class BasicModule extends javax.swing.JPanel {

    private final Aplication app;
    private int selected = -1;
    private final Color colorSelected = new Color(127, 189, 255);
    private final Color colorBg = new Color(120, 154, 234);
    private ActionListener acListener;

    /**
     * Creates new form BasicModule
     *
     * @param app
     * @param opciones
     */
    public BasicModule(Aplication app, ArrayList<ProgAction> opciones, ActionListener acListener) {
        this.app = app;
        this.acListener = acListener;
        initComponents();
        createComponents(opciones);
    }

    private void createComponents(ArrayList<ProgAction> opciones) {
        setBackground(new Color(255, 255, 255, 5));
        panelMenu.setBackground(new Color(255, 255, 255, 80));
        panelContenedor.setBackground(new Color(255, 255, 255, 80));
        panelContenedor.add(new JLabel("INVENTARIO"));

        panelMenu.setLayout(new GridLayout(10, 1, 2, 5));
        int i = 0;
        for (Action get : opciones) {
            MyMenuItem myMenuItem = new MyMenuItem(get, colorBg);
            myMenuItem.setOrden(i++);
            myMenuItem.addActionListener(acListener);
            myMenuItem.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    updateSel(((MyMenuItem) e.getSource()).getOrden());
                }
            });
            panelMenu.add(myMenuItem);
        }
    }

    private void updateSel(int sel) {
        if (selected != -1) {
            panelMenu.getComponent(selected).setBackground(colorBg);
        }
        selected = sel;
        panelMenu.getComponent(sel).setBackground(colorSelected);
    }

    public void mostrarPanel(Component panel) {
        panelContenedor.removeAll();
        panelContenedor.setLayout(new BorderLayout());
        panelContenedor.add(panel, BorderLayout.CENTER);
        panelContenedor.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        panelContenedor = new javax.swing.JPanel();

        panelMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        panelContenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables

}
