package com.bacon.gui;

import com.bacon.Aplication;
import com.bacon.domain.Table;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.beans.PropertyChangeEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;
import org.dz.PanelCapturaMod;

/**
 *
 * @author lrod
 */
public class PanelTakeOrders extends PanelCapturaMod {

    private final Aplication app;

    /**
     * Creates new form PanelTakeOrders
     *
     * @param app
     */
    public PanelTakeOrders(Aplication app) {
        this.app = app;
        initComponents();
        createComponents();
    }

    private void createComponents() {

        JPanel pnTables = new JPanel();
        pnTables.setLayout(new FlowLayout());

        ArrayList<Table> tableslList = app.getControl().getTableslList("", "");
        for (Table table : tableslList) {

            JButton btn = new JButton(table.getName());
            btn.setText("<html>Mesa:<br><font color=blue size=+1>" + table.getName() + "</html>");
            btn.setPreferredSize(new Dimension(100, 100));
            btn.setBorder(BorderFactory.createLineBorder(Color.green, 1, true));

            pnTables.add(btn);
        }

        jSplitPane1.setLeftComponent(pnTables);
        jSplitPane1.setRightComponent(new JPanel());
        jSplitPane1.setDividerLocation(0.5);
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
