package com.bacon.gui;

import com.bacon.Aplication;
import com.bacon.ProgAction;
import com.bacon.domain.Invoice;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.beans.PropertyChangeEvent;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import org.dz.PanelCapturaMod;
import org.dz.TextFormatter;

/**
 *
 * @author lrod
 */
public class PanelPayInvoice extends PanelCapturaMod {

    private final Aplication app;
    private final Invoice invoice;
    private ProgAction acEfecty;

    /**
     * Creates new form PanelPayInvoice
     *
     * @param app
     * @param invoice
     */
    public PanelPayInvoice(Aplication app, Invoice invoice) {
        this.app = app;
        this.invoice = invoice;
        
        acEfecty = new ProgAction("Efectivo",
                new ImageIcon(app.getImgManager().getImagen(app.getFolderIcons() + "cash.png", 24, 24)), "Efectivo", 'e') {
            public void actionPerformed(ActionEvent e) {
//                        salir(0);
            }
        };
        
        initComponents();
        createComponents();
    }

    private void createComponents() {

        Font f = new Font("Sans serif", 1, 16);
        Font f2 = new Font("Tahoma", 1, 16);

        

        lbTitle.setText(invoice.getFactura());
        lbInvoice.setText("Factura");
        lbTitle.setForeground(Color.blue.darker());
        lbTitle.setFont(f2);

        lbSubt.setText("Subtotal");
        lbValSubt.setText(app.getDCFORM_P().format(invoice.getValor().doubleValue()));
        lbValSubt.setFont(f2);
        lbVar.setText(invoice.getTipoEntrega() == 1 ? "Servicio" : "Domicilio");
        lbValVar.setText(app.getDCFORM_P().format(invoice.getTipoEntrega() == 1 ? invoice.getValueService() : invoice.getValorDelivery().doubleValue()));
        lbValVar.setFont(f2);
        lbTotal.setText("Total");
        lbValTot.setText(app.getDCFORM_P().format(invoice.getValor().add(invoice.getValorDelivery()).doubleValue() + invoice.getValueService()));
        lbValTot.setFont(f2);

//        lbValSubt.setFont(new Font("Sans", 1, 16));
//        lbValSubt.setText(app.getDCFORM_P().format(invoice.getValor().doubleValue()));

        regEfect.addActionListener(acEfecty);
        regEfect.setLabelText("Efectivo");
        regEfect.setFontCampo(f);
        
        regEfect.setTextAligment(SwingConstants.RIGHT);
        regEfect.setDocument(TextFormatter.getDoubleLimiter());
        regEfect.setText(app.getDCFORM_W().format(invoice.getValorTotal().doubleValue()));
        regTransfer.setLabelText("Tranferencias");
        regTransfer.setFontCampo(f);
        regTransfer.setTextAligment(SwingConstants.RIGHT);
        regTransfer.setDocument(TextFormatter.getDoubleLimiter());
        regTransfer.setText("0");

        btPagar.setText("Pagar");

        regEfect.addCaretListener(new CaretListener() {
            @Override
            public void caretUpdate(CaretEvent e) {
                calcularValores(1);
            }

        });

        regTransfer.addCaretListener(new CaretListener() {
            @Override
            public void caretUpdate(CaretEvent e) {
                calcularValores(2);
            }

        });
    }

    private void calcularValores(int reg) {
        try {
            double total = invoice.getValorTotal().doubleValue();
            double efectivo = app.getDCFORM_P().parse(regEfect.getText()).doubleValue();
            double transfer = app.getDCFORM_P().parse(regTransfer.getText()).doubleValue();

            switch (reg) {
                case 1:
                    transfer = total - efectivo;
                    regTransfer.setText(String.valueOf(app.getDCFORM_W().format(transfer)));
                    break;
                case 2:
                    efectivo = total - transfer;
                    regEfect.setText(String.valueOf(app.getDCFORM_W().format(efectivo)));
                    break;
            }

        } catch (Exception e) {
            System.err.println(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        regEfect = new com.bacon.gui.util.Registro(0, "","0",140,140, acEfecty);
        registro2 = new com.bacon.gui.util.Registro();
        regTransfer = new com.bacon.gui.util.Registro(0, "","0",140);
        btPagar = new javax.swing.JButton();
        lbInvoice = new javax.swing.JLabel();
        lbValSubt = new javax.swing.JLabel();
        lbValVar = new javax.swing.JLabel();
        lbSubt = new javax.swing.JLabel();
        lbVar = new javax.swing.JLabel();
        lbValTot = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();

        lbTitle.setBackground(new java.awt.Color(195, 195, 195));
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTitle.setText("jLabel1");
        lbTitle.setOpaque(true);

        btPagar.setText("jButton1");

        lbInvoice.setBackground(new java.awt.Color(150, 156, 158));
        lbInvoice.setText("jLabel1");
        lbInvoice.setOpaque(true);

        lbValSubt.setBackground(new java.awt.Color(195, 195, 195));
        lbValSubt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbValSubt.setText("jLabel1");
        lbValSubt.setOpaque(true);

        lbValVar.setBackground(new java.awt.Color(195, 195, 195));
        lbValVar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbValVar.setText("jLabel1");
        lbValVar.setOpaque(true);

        lbSubt.setBackground(new java.awt.Color(150, 156, 158));
        lbSubt.setText("jLabel1");
        lbSubt.setOpaque(true);

        lbVar.setBackground(new java.awt.Color(150, 156, 158));
        lbVar.setText("jLabel1");
        lbVar.setOpaque(true);

        lbValTot.setBackground(new java.awt.Color(195, 195, 195));
        lbValTot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbValTot.setText("jLabel1");
        lbValTot.setOpaque(true);

        lbTotal.setBackground(new java.awt.Color(150, 156, 158));
        lbTotal.setText("jLabel1");
        lbTotal.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btPagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(registro2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(regTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regEfect, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbVar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbSubt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbValVar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbValSubt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbValTot, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lbInvoice)
                            .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSubt)
                            .addComponent(lbValSubt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbValVar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbVar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbValTot, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regEfect, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btPagar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(registro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbInvoice, lbTitle});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPagar;
    private javax.swing.JLabel lbInvoice;
    private javax.swing.JLabel lbSubt;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbValSubt;
    private javax.swing.JLabel lbValTot;
    private javax.swing.JLabel lbValVar;
    private javax.swing.JLabel lbVar;
    private com.bacon.gui.util.Registro regEfect;
    private com.bacon.gui.util.Registro regTransfer;
    private com.bacon.gui.util.Registro registro2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt) {

    }
}
