/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bacon.gui;

import com.bacon.Aplication;
import com.bacon.domain.ConfigDB;
import com.bacon.gui.util.Registro;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import org.dz.TextFormatter;

/**
 *
 * @author ballestax
 */
public class PanelConfigOthers extends javax.swing.JPanel implements ActionListener {

    public static final String ACTION_APPLY = "ACTION_SAVE";

    private final Aplication app;
    private String selectedPrinter;
    private String printerName;

    /**
     * Creates new form PanelConfigMotor
     *
     * @param app
     */
    public PanelConfigOthers(Aplication app) {
        this.app = app;
        initComponents();
        createComponents();
    }

    private void createComponents() {
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));

        ConfigCont cCont = new ConfigCont(app);
        cCont.setTitle("Valor del domicilio");
        cCont.addCampo(new Registro(BoxLayout.X_AXIS, "Domicilio", "", 100));
        jPanel1.add(cCont);
        jPanel1.add(Box.createVerticalStrut(5));

        cCont = new ConfigCont(app);
        cCont.setTitle("Nombre del documento");
        cCont.addCampo(new Registro(BoxLayout.X_AXIS, "Documento", "", 100));
        jPanel1.add(cCont);
        jPanel1.add(Box.createVerticalStrut(5));

        cCont = new ConfigCont(app);
        cCont.setTitle("Numero de ceros a formatear el consecutivo");
        cCont.addCampo(new Registro(BoxLayout.X_AXIS, "Ceros", "", 100));
        jPanel1.add(cCont);
        jPanel1.add(Box.createVerticalStrut(5));

        cCont = new ConfigCont(app);
        cCont.setTitle("Prefijo del consecutivo");
        cCont.addCampo(new Registro(BoxLayout.X_AXIS, "Prefijo", "", 100));
        jPanel1.add(cCont);
        jPanel1.add(Box.createVerticalStrut(5));

        cCont = new ConfigCont(app);
        cCont.setTitle("Permitir facturar sin existencias");
        Registro registro = new Registro(BoxLayout.X_AXIS, "Permitir", false, 100);
        registro.setFontCampo(new Font("Arial", 0, 16));
        cCont.addCampo(registro);
        jPanel1.add(cCont);
        jPanel1.add(Box.createVerticalStrut(5));

        cCont = new ConfigCont(app);
        cCont.setTitle("Permitir imprimir pedido previo");
        registro = new Registro(BoxLayout.X_AXIS, "Permitir", false, 100);
        registro.setFontCampo(new Font("Arial", 0, 16));
        cCont.addCampo(registro);
        jPanel1.add(cCont);
        jPanel1.add(Box.createVerticalStrut(5));

        btApply.setText("Aplicar");
        btApply.setActionCommand(ACTION_APPLY);
        btApply.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbInfo = new javax.swing.JLabel();
        regPrintPrev = new javax.swing.JCheckBox();
        regDelivery = new com.bacon.gui.util.Registro(BoxLayout.X_AXIS, "Domicilio", "");
        lbInfo1 = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        regShowExclusions = new javax.swing.JCheckBox();
        lbInfo2 = new javax.swing.JLabel();
        lbInfo3 = new javax.swing.JLabel();
        regInvoiceOutStock = new javax.swing.JCheckBox();
        lbInfo4 = new javax.swing.JLabel();
        regPrefix = new com.bacon.gui.util.Registro(BoxLayout.X_AXIS, "Domicilio", "");
        lbInfo5 = new javax.swing.JLabel();
        regZeros = new com.bacon.gui.util.Registro(BoxLayout.X_AXIS, "Domicilio", "");
        regDocument = new com.bacon.gui.util.Registro(BoxLayout.X_AXIS, "Domicilio", "");
        lbInfo6 = new javax.swing.JLabel();
        btApply = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        lbInfo.setText("jLabel2");
        lbInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        regPrintPrev.setText("jCheckBox1");

        lbInfo1.setText("jLabel2");
        lbInfo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTitle.setBackground(java.awt.Color.lightGray);
        lbTitle.setOpaque(true);

        regShowExclusions.setText("jCheckBox1");

        lbInfo2.setText("jLabel2");
        lbInfo2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbInfo3.setText("jLabel2");
        lbInfo3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        regInvoiceOutStock.setText("jCheckBox1");

        lbInfo4.setText("jLabel2");
        lbInfo4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbInfo5.setText("jLabel2");
        lbInfo5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbInfo6.setText("jLabel2");
        lbInfo6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 337, Short.MAX_VALUE)
                        .addComponent(btApply, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btApply, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApply;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbInfo1;
    private javax.swing.JLabel lbInfo2;
    private javax.swing.JLabel lbInfo3;
    private javax.swing.JLabel lbInfo4;
    private javax.swing.JLabel lbInfo5;
    private javax.swing.JLabel lbInfo6;
    private javax.swing.JLabel lbTitle;
    private com.bacon.gui.util.Registro regDelivery;
    private com.bacon.gui.util.Registro regDocument;
    private javax.swing.JCheckBox regInvoiceOutStock;
    private com.bacon.gui.util.Registro regPrefix;
    private javax.swing.JCheckBox regPrintPrev;
    private javax.swing.JCheckBox regShowExclusions;
    private com.bacon.gui.util.Registro regZeros;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (ACTION_APPLY.equals(e.getActionCommand())) {
            String value = regDelivery.getText();
            app.getControl().addConfig(new ConfigDB(com.bacon.Configuration.DELIVERY_VALUE, ConfigDB.DOUBLE, value));

            boolean selected = regPrintPrev.isSelected();
            app.getConfiguration().setProperty(com.bacon.Configuration.PRINT_PREV_DELIVERY, String.valueOf(selected));

            boolean selected2 = regShowExclusions.isSelected();
            app.getConfiguration().setProperty(com.bacon.Configuration.SHOW_EXCLUSIONS, String.valueOf(selected2));

            boolean selected3 = regInvoiceOutStock.isSelected();
            app.getConfiguration().setProperty(com.bacon.Configuration.INVOICE_OUT_STOCK, String.valueOf(selected3));

            String prefix = regPrefix.getText();
            app.getControl().addConfig(new ConfigDB(com.bacon.Configuration.PREFIX_INVOICES, ConfigDB.STRING, prefix));

            String ceros = regZeros.getText();
            app.getControl().addConfig(new ConfigDB(com.bacon.Configuration.ZEROS_INVOICES, ConfigDB.STRING, ceros));

            String docName = regDocument.getText();
            app.getControl().addConfig(new ConfigDB(com.bacon.Configuration.DOCUMENT_NAME, ConfigDB.STRING, docName));

            app.getConfiguration().save();
        }
    }
}
