package com.bacon.gui;

import com.bacon.Aplication;
import com.bacon.GUIManager;
import com.bacon.domain.Invoice;
import com.bacon.domain.ProductoPed;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.List;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.MediaPrintableArea;

/**
 *
 * @author lrod
 */
public class PanelConfirmPedido extends javax.swing.JPanel implements ActionListener {

    private final Aplication app;
    private final Invoice invoice;

    /**
     * Creates new form PanelConfirmPedido
     *
     * @param app
     * @param invoice
     */
    public PanelConfirmPedido(Aplication app, Invoice invoice) {
        this.app = app;
        this.invoice = invoice;
        initComponents();
        createComponents();
        setupInvoice();

    }

    public void createComponents() {

        btPrint.setText("Imprimir");
        btPrint.setActionCommand(AC_PRINT_BILL);
        btPrint.addActionListener(this);

        btConfirm.setText("Guardar");
        btConfirm.setActionCommand(AC_SAVE_BILL);
        btConfirm.addActionListener(this);

    }
    public static final String AC_SAVE_BILL = "AC_SAVE_BILL";
    public static final String AC_PRINT_BILL = "AC_PRINT_BILL";

    public void setupInvoice() {
        if (invoice != null) {
            lbTitle.setText("PEDIDO: " + invoice.getFactura());

            StringBuilder textInfo = new StringBuilder("<html>");
            textInfo.append("<table  width=\"100%\" cellspacing=\"10\" border=\"1\"><tr><td>Mesa:").append(1);
            textInfo.append("</td><td>Mesero: ").append("Mesero");
            textInfo.append("</td></tr></table></html>");
//            System.out.println(textInfo.toString());
            lbInfo.setText(textInfo.toString());

            StringBuilder str = new StringBuilder();
            str.append("<html><table width=\"600\" cellspacing=\"0\" border=\"1\">");
            str.append("<tr bgcolor=\"#A4C1FF\">");
            str.append("<td>").append("Producto").append("</td>");
//            str.append("<td>").append("Codigo").append("</td>");
            str.append("<td>").append("Cant.").append("</td>");
            str.append("<td>").append("V. Uni").append("</td>");
            str.append("<td>").append("V. total").append("</td></tr>");
            List<ProductoPed> productos = invoice.getProducts();
            System.out.println("products:" + productos.size());
            double total = 0;
            for (ProductoPed product : productos) {
//            System.err.println(product);
                int cantidad = product.getCantidad();
                double price = product.getValueAdicionales() + product.getProduct().getPrice();
                total += cantidad * price;
                str.append("<tr><td bgcolor=\"#F6FFDB\">").append(product.getProduct().getName().toUpperCase());
                str.append("<br><font size=2>").append(product.getStAdicionales()).append("</font></td>");
//                str.append("<td bgcolor=\"#FFFFFF\">").append(product.getProduct().getCode()).append("</td>");
                str.append("<td bgcolor=\"#FFFFFF\" align=\"right\">").append(app.DCFORM_P.format(cantidad)).append("</td>");
                str.append("<td bgcolor=\"#FFFFFF\" align=\"right\">").append(app.DCFORM_P.format(price)).append("</td>");
                str.append("<td bgcolor=\"#FFFFFF\" align=\"right\">").append(app.DCFORM_P.format(cantidad * price)).append("</td>");
                str.append("</tr>");
            }
            str.append("</table></html>");

            lbTable.setText(str.toString());

            lbTotal.setText("<html><font size=+1 color=red>" + app.getCurrencyFormat().format(total) + "</html>");

        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {        
        if (AC_PRINT_BILL.equals(e.getActionCommand())) {

        } else if (AC_SAVE_BILL.equals(e.getActionCommand())) {
            app.getControl().addInvoice(invoice);
        }

    }

    private void imprimirFacturaSalida(Invoice invoice, String printerName) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lbTable = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        lbInfo = new javax.swing.JLabel();
        btConfirm = new javax.swing.JButton();
        btPrint = new javax.swing.JButton();

        lbTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 192, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTable, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirm;
    private javax.swing.JButton btPrint;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbTable;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbTotal;
    // End of variables declaration//GEN-END:variables
}
