package com.bacon.gui;

import com.bacon.Aplication;
import com.bacon.domain.Item;
import com.bacon.domain.Location;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.math.BigDecimal;
import java.util.ArrayList;
import org.apache.commons.lang3.StringUtils;
import org.dz.PanelCapturaMod;

/**
 *
 * @author lrod
 */
public class PanelAddExtra extends PanelCapturaMod implements ActionListener{

    private final Aplication app;
    private String lb1, lb2, lb3, lb4, lb5;
    private int width = 100;

    /**
     * Creates new form PanelAddExtra
     * @param app
     * @param pcl
     */
    public PanelAddExtra(Aplication app, PropertyChangeListener pcl) {
        this.app = app;
        
        initComponents();
        createComponents(); 
        
        addPropertyChangeListener(pcl);
    }

    private void createComponents() {
        lb1 = "Tipo";
        lb2 = "Categoria";
        lb3 = "Valor";
        lb4 = "Nota";
        lb5 = "Descripción";
        
        regTipo.setLabelText(lb1);
        regCategory.setLabelText(lb2);
        regDesc.setLabelText(lb5);
        regValor.setLabelText(lb3);
        regNote.setLabelText(lb4);
        
        String[] tipo = {"Salida","Entrada"};
        regTipo.setText(tipo);
        
        btSave.setText("Agregar");
        btSave.setActionCommand(AC_ADD_EXTRA);
        btSave.addActionListener(app);
        
    }
    
    private void checkExtra() {
        
    }
    
    
    private static final String AC_ADD_EXTRA = "AC_ADD_EXTRA";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        regTipo = new com.bacon.gui.util.Registro(0,lb1, new String[0],width);
        regCategory = new com.bacon.gui.util.Registro(0, lb2, new String[0], width);
        regValor = new com.bacon.gui.util.Registro(0, lb3, "", width);
        regNote = new com.bacon.gui.util.Registro(0, lb4, "", width);
        regDesc = new com.bacon.gui.util.Registro(0, lb5, "", width);
        btSave = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(147, 112, 112));
        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);

        btSave.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 272, Short.MAX_VALUE)
                        .addComponent(btSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSave)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {regCategory, regDesc, regNote, regTipo, regValor});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSave;
    private javax.swing.JLabel jLabel1;
    private com.bacon.gui.util.Registro regCategory;
    private com.bacon.gui.util.Registro regDesc;
    private com.bacon.gui.util.Registro regNote;
    private com.bacon.gui.util.Registro regTipo;
    private com.bacon.gui.util.Registro regValor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(AC_ADD_EXTRA.equals(e.getActionCommand())){
            
        }
    }
}
